# WPS enabled — weak
interface=wlan0
ssid=LAB-WPS
hw_mode=g
channel=6
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_passphrase=StrongPass123
wps_state=2
ap_setup_locked=0
eap_server=1
wps_pin=12345670
