import { Link } from 'react-router-dom'
import { ArrowRight } from 'lucide-react'
import learningPaths from '@/content/learning-paths.json'
import { TOTAL_CHALLENGES, TOTAL_PCAPS, getStatsForPath } from '@/content/stats'
import { PREVIEW_MODULE_COUNT } from '@/lib/contentAccess'
import { useSession } from '@/lib/session'
import { isSignedIn, STATE_META } from '@/lib/access'
import { StateChip } from '@/components/account/StateChip'

const availablePaths = learningPaths.filter(path => path.status === 'available')
const available = availablePaths[0]
const wirelessStats = getStatsForPath('wireless-pentesting')
const planned = learningPaths.filter(path => path.status !== 'available')

export function PublicHome() {
  const { userState, ready, accountLoading } = useSession()
  const signedIn = (ready || accountLoading) && isSignedIn(userState)
  return <div className="public-home">
    <section className="public-hero"><div className="public-container public-hero-grid"><div className="public-hero-copy"><p className="public-eyebrow">SecCraft / Practical security education</p><h1>Learn cybersecurity <em>by doing.</em></h1><p className="public-lead">Learn. Practice. Investigate. Improve.</p><p>Understand the protocol. Examine the evidence. Test your interpretation. Document what you can prove.</p><div className="public-actions"><Link className="public-primary" to="/app">{signedIn ? 'Open your workspace' : 'Start the Preview Curriculum'} <ArrowRight size={17} aria-hidden="true" /></Link><Link className="public-secondary" to="/paths">Explore learning paths</Link></div><p className="public-note">{PREVIEW_MODULE_COUNT} preview modules without an account. Practice progress stays in this browser.</p>{signedIn && <div className="public-session">{accountLoading ? <span role="status">Checking account status…</span> : <><StateChip state={userState} /><span>{STATE_META[userState].nextAction}</span></>}</div>}</div>
      <div className="public-artifact" aria-label="Available Wireless Pentesting curriculum"><div className="public-artifact-head"><span>CURRICULUM / 01</span><span>AVAILABLE</span></div><h2>{available?.title}</h2><p>{available?.description}</p><div className="public-artifact-counts">{[[wirelessStats.modules,'modules'],[wirelessStats.lessons,'lessons'],[wirelessStats.labs,'labs'],[TOTAL_PCAPS,'captures']].map(([value,label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><ol className="public-artifact-phases">{available?.phases.map((phase, index) => <li key={phase.id}><span>{String(index + 1).padStart(2,'0')}</span><strong>{phase.name}</strong><small>{phase.modules.length} modules</small></li>)}</ol><Link to={available ? `/paths/${available.id}` : '/paths'}>View the curriculum <ArrowRight size={16} aria-hidden="true" /></Link></div>
    </div></section>
    <section className="public-method" id="method"><div className="public-container"><div className="public-method-title"><p className="public-eyebrow">The approach</p><h2>Understand the Protocol.{' '}<br />Test the Implementation.</h2><p>Technical understanding comes before the tool. Work from authored lessons through supplied artifacts and document the limits of your evidence.</p></div><ol>{[
      ['Learn', 'Follow authored lessons and objectives in a structured module sequence.'],
      ['Practice', `Use ${TOTAL_PCAPS} supplied captures and local-first lab tools.`],
      ['Investigate', `Work through ${TOTAL_CHALLENGES} self-review challenges. These are not trusted grading.`],
      ['Assess', 'Try independent cases and local self-review; results are not independently graded.'],
      ['Improve', 'Record findings, revisit weak areas and build a clearer explanation.'],
    ].map(([title, body], index) => <li key={title}><span>{String(index + 1).padStart(2,'0')}</span><div><h3>{title}</h3><p>{body}</p></div></li>)}</ol></div></section>
    <section className="public-access-section" aria-labelledby="actual-practice"><div className="public-container"><p className="public-eyebrow">What you will actually do</p><h2 id="actual-practice">Work with evidence, not just descriptions.</h2><div className="public-access-rows"><div><span>Wireless</span><h3>Inspect 802.11 captures</h3><p>Use supplied synthetic captures to interpret frames, explain limits and choose a safe next step.</p><Link to="/paths/wireless-pentesting">Explore wireless →</Link></div><div><span>Android</span><h3>Review Android source cases</h3><p>Trace component and data boundaries in supplied source. Building an APK or running an emulator is optional and not provided as a measured result.</p><Link to="/paths/android-pentesting">Explore Android →</Link></div><div><span>Beyond the current catalogue</span><h3>AI / LLM Security</h3><p>Planned, not an available course or assessment.</p><Link to="/paths">See the roadmap →</Link></div></div></div></section>
    <section className="public-curriculum"><div className="public-container public-curriculum-grid"><div><p className="public-eyebrow">Current curriculum</p><h2>Available paths. Actual starting points.</h2><p>Explore authored curriculum and practice with supplied evidence. Android uses source-backed cases; wireless uses synthetic capture analysis. Neither path claims independently verified field competence.</p><ul>{availablePaths.map(path => <li key={path.id}><Link to={`/paths/${path.id}`}>{path.title} <ArrowRight size={16} aria-hidden="true" /></Link><p>{path.description}</p></li>)}</ul></div><div className="public-planned"><h3>Domains on the roadmap</h3><p>These are planned entries, not available courses.</p><ul>{planned.map(path => <li key={path.id}><span>{path.title}</span><small>Planned</small></li>)}</ul></div></div></section>
    <section className="public-access-section"><div className="public-container"><p className="public-eyebrow">Access and records</p><h2>Begin now. Know what each record means.</h2><div className="public-access-rows"><div><span>01 / Preview</span><h3>Guest, pending, rejected or suspended</h3><p>Preview Curriculum and browser-local, unverified practice XP. After signup and email confirmation, an account request enters Pending approval before the owner decides.</p></div><div><span>02 / Full</span><h3>Active or owner account</h3><p>Full Curriculum experience and separate account-held progress. Server access remains authoritative.</p></div><div><span>03 / Boundaries</span><h3>No trusted grading yet</h3><p>Imports and assessment attempts remain unverified. No trusted live grader issues XP or certificates. Preview and Full are product experiences, not a content security boundary.</p></div></div></div></section>
    <section className="public-close"><div className="public-container"><p className="public-eyebrow">Begin with the evidence</p><h2>Go from reading to reasoning.</h2><p>Explore the Preview Curriculum now. An approved account adds account-backed records when you need them.</p><div className="public-actions"><Link className="public-primary" to="/app">Open the workspace →</Link>{!signedIn && <Link className="public-secondary" to="/signup">Request an account</Link>}</div><p className="public-note">For authorized security learning and testing only. No accredited certification is issued.</p></div></section>
  </div>
}
