#!/usr/bin/env python3
"""Original, deterministic evidence-only foundations case. Never uses a radio.
EPB timestamps are split at 2**32, not 1,000,000 (also fixed in the legacy writer).
--check compares generated bytes/exports/manifest without rewriting the release.
"""
from pathlib import Path
import argparse
import io
import zipfile
import hashlib
import json
import struct
from datetime import datetime, timezone
from wififorge_labkit import beacon_body, ie_rsn, ie_ssid, ie_supported_rates, mgmt_frame, radiotap

ROOT = Path(__file__).resolve().parents[1]
DEST = ROOT / 'frontend/public/wireless-foundations/WF-FND-01'
START = int(datetime(2026, 9, 1, 9, tzinfo=timezone.utc).timestamp()) * 1_000_000
A1, A2, A3, A4 = [bytes.fromhex('0200000010' + suffix) for suffix in ('01','02','03','04')]
C1, C2 = bytes.fromhex('020000002001'), bytes.fromhex('060000002002')
BROADCAST = b'\xff' * 6
NAME = 'Aster-Lab'

def block(kind, body):
    assert len(body) % 4 == 0
    length = 12 + len(body)
    return struct.pack('<II', kind, length) + body + struct.pack('<I', length)

def capture(frames, start):
    data = block(0x0A0D0D0A, struct.pack('<IHHq', 0x1A2B3C4D, 1, 0, -1))
    data += block(1, struct.pack('<HHIHH',127,0,65535,9,1) + b'\x06\0\0\0' + bytes(4))
    for index, frame in enumerate(frames,1):
        ticks = start + index * 2000
        data += block(6, struct.pack('<IIIII',0,ticks >> 32,ticks & 0xffffffff,len(frame),len(frame)) + frame + bytes((-len(frame)) % 4))
    return data

def frames(followup=False):
    result=[]
    def add(subtype,dst,src,bssid,body):
        # Fixed fabricated receive power/frequency: no noise measurement or field RSSI claim.
        packet = radiotap(2437,-47,rate=2,chan_flags=0x00a0) + mgmt_frame(subtype,dst,src,bssid,body,seq=len(result))
        result.append(packet)
    def beacon(ap,ssid,caps):
        add(8,BROADCAST,ap,ap,beacon_body(ssid,6,ies=[ie_rsn(caps=caps)]))
    beacon(A1,NAME if followup else '',0x0080)
    beacon(A2,NAME,0x00c0)
    beacon(A3,NAME,0x0080)
    if followup: return result
    beacon(A4,'Nearby-Example',0x0080)
    add(4,BROADCAST,C1,BROADCAST,ie_ssid(NAME)+ie_supported_rates())
    add(5,C1,A1,A1,beacon_body(NAME,6,ies=[ie_rsn(caps=0x0080)]))
    add(11,A1,C1,A1,struct.pack('<HHH',0,1,0))
    add(11,C1,A1,A1,struct.pack('<HHH',0,2,0))
    add(0,A1,C1,A1,struct.pack('<HH',0x0411,10)+ie_ssid(NAME)+ie_supported_rates()+ie_rsn(caps=0x0080))
    add(1,C1,A1,A1,struct.pack('<HHH',0x0411,0,0xc001)+ie_supported_rates())
    add(4,BROADCAST,C2,BROADCAST,ie_ssid('')+ie_supported_rates())
    beacon(A2,NAME,0x00c0)
    add(12,C1,A1,A1,struct.pack('<H',7))
    return result

def decoded(packet):
    # Narrow export parser for these management-only fixtures. Do not inherit the
    # legacy RSN group-suite offset bug (the suite type is value[5], not value[4]).
    offset=struct.unpack_from('<H',packet,2)[0]
    raw=packet[offset:]; subtype=(raw[0] >> 4) & 15; body=raw[24:]
    mac=lambda b: ':'.join(f'{x:02x}' for x in b)
    row={'type':0,'subtype':subtype,'source':mac(raw[10:16]),'destination':mac(raw[4:10]),'bssid_field':mac(raw[16:22]),'frequency_mhz':struct.unpack_from('<H',packet,18)[0],'signal_dbm':struct.unpack_from('<b',packet,22)[0]}
    starts={8:12,5:12,4:0,0:4,1:6}
    if subtype in starts:
        pos=starts[subtype]
        while pos < len(body):
            tag,size=body[pos:pos+2]; value=body[pos+2:pos+2+size];pos+=2+size
            if tag==0: row['ssid']=value.decode('utf-8')
            if tag==3: row['advertised_channel']=value[0]
            if tag==48:
                # This case deliberately has one pairwise suite and one AKM.
                assert len(value)==20 and struct.unpack_from('<H',value,6)[0]==1 and struct.unpack_from('<H',value,12)[0]==1
                row.update(group_cipher=value[5],pairwise_cipher=value[11],akm=value[17],rsn_capabilities=struct.unpack_from('<H',value,18)[0])
    if subtype==11: row.update(authentication_algorithm=struct.unpack_from('<H',body,0)[0],authentication_sequence=struct.unpack_from('<H',body,2)[0],status_code=struct.unpack_from('<H',body,4)[0])
    if subtype==1: row['status_code']=struct.unpack_from('<H',body,2)[0]
    if subtype==12: row['reason_code']=struct.unpack_from('<H',body,0)[0]
    return row

def export(packets,start):
    rows=[{'frame':index,'timestamp_epoch_us':start+index*2000,**decoded(packet)} for index,packet in enumerate(packets,1)]
    return (json.dumps({'provenance':'Deterministic synthetic teaching frames, not a field capture. Derived read-only view; no execution or grading.', 'frames':rows},indent=2)+'\n').encode()

def build():
    generated={}
    for name,is_followup,start in [('baseline',False,START),('follow-up',True,START+60_000_000)]:
        packets=frames(is_followup)
        generated[name+'.pcapng']=capture(packets,start)
        generated[name+'-frames.json']=export(packets,start)
    authored={p.name:p.read_bytes() for p in DEST.iterdir() if p.suffix in ('.md','.csv')}
    assert {'README.md','scope.md','authorized-inventory.csv','worksheet.md','self-review.md'} <= authored.keys()
    contents={**authored,**generated}
    generated['SHA256SUMS']=''.join(f'{hashlib.sha256(data).hexdigest()}  {name}\n' for name,data in sorted(contents.items())).encode()
    return generated

def archive(generated):
    contents={p.name:p.read_bytes() for p in DEST.iterdir() if p.suffix in ('.md','.csv')}
    contents.update(generated)
    buffer=io.BytesIO()
    with zipfile.ZipFile(buffer,'w',compression=zipfile.ZIP_DEFLATED) as z:
        for name,data in sorted(contents.items()):
            info=zipfile.ZipInfo('WF-FND-01/'+name,date_time=(2026,9,1,9,0,0))
            info.compress_type=zipfile.ZIP_DEFLATED; info.external_attr=0o644 << 16
            z.writestr(info,data)
    return buffer.getvalue()

if __name__=='__main__':
    args=argparse.ArgumentParser();args.add_argument('--check',action='store_true');opts=args.parse_args()
    generated=build()
    targets={DEST/name:data for name,data in generated.items()}
    targets[DEST.parent/'WF-FND-01.zip']=archive(generated)
    for target,data in targets.items():
        if opts.check:
            assert target.read_bytes()==data, f'Stale case file: {target.name}; run generator'
        else: target.write_bytes(data)
    print('WF-FND-01 deterministic files and manifest '+('match' if opts.check else 'written'))
